version: '3.3'
services:
  dlc-oracle:
    container_name: 'dlc-oracle'
    build: '.'
    ports:
      - '80:80'
    volumes:
      - oracle-data:/root
    restart: always
    secrets:
      - oracle_pw
    depends_on:
      - 'mongo'
    command: sh -c "./dlc-oracle rest --password /run/secrets/oracle_pw"
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  oracle-data:
  mongo-data:

secrets:
  oracle_pw:
    external: true