version: '3.3'
services:
  dlc-oracle:
    container_name: 'dlc-oracle'
    build: '.'
    ports:
      - '3000:3000'
    volumes:
      - '.:/go/src/app'
    depends_on:
      - 'mongo'
    command: sh -c "go run util/createkey.go && ./dlc-oracle rest"
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27017:27017'